### ISSUE TITLE
deepin desktop doesn't install because add-apt-repository is not installed

### ISSUE THREAD

**Issue by eternaldensity** [tuanpham-dev/termux-ubuntu#1]
The ubuntudde-dev ppa does not get added because add-apt-repository is not found.

Running ```sudo apt-get install software-properties-common``` first is necessary.

**Comment by tuanpham-dev** [comment]
Hi, this was my experiment for testing if Deepin Desktop is installable. Now I reverted back to XFCE to avoid any confusion. I will update to Deepin Desktop later.
