### ISSUE TITLE
Crypted script setup-audio.sh

### ISSUE THREAD

**Issue by XopmoH97** [tuanpham-dev/termux-ubuntu#11]
![Screenshot_2021-07-09-22-45-01-81_84d3000e3f4017145260f7618db1d683](https://user-images.githubusercontent.com/51299245/125128877-53177900-e107-11eb-9140-a33ba1fc1fe0.jpg)
What is this??? And why this script crypted?

**Comment by tuanpham-dev** [comment]
@XopmoH97 You better ask Andronix Team. Maybe they do not want us to know how they do with audio fix. See https://docs.andronix.app/hardware/sound
