### ISSUE TITLE
Failed start chromium in VNC session

### ISSUE THREAD

**Issue by XopmoH97** [tuanpham-dev/termux-ubuntu#12]
![Screenshot_2021-07-09-22-35-17-47_8659c1e795b4b4239e38d87c88c077b3](https://user-images.githubusercontent.com/51299245/125129121-9ffb4f80-e107-11eb-8d1f-382bf680543d.jpg)
How to fix this errors???
My device: Oppo A74 (Android 11), arm64

**Comment by tuanpham-dev** [comment]
@XopmoH97 It should be fixed now
