### ISSUE TITLE
Chromium is playing Youtube video but not with sounds/audio.

### ISSUE THREAD

**Issue by arcans** [tuanpham-dev/termux-ubuntu#13]
How can I play Youtube videos with sounds/audio?

**Comment by tuanpham-dev** [comment]
@arcans - Did you run this after installing? Could you exit ubuntu and termux then start ubuntu again?

**Comment by arcans** [comment]
Yes, I ran it after installing.
And then as per your suggestion, I tried to force stop termux so that I could kill all processes completely. But still didn't play audio.

>> My device is Xiaomi 6/128

**Comment by arcans** [comment]
I saw that icon but it is not enabled.
![Uploading Screenshot_2021-07-13-12-55-05-054_com.realvnc.viewer.android.jpg…]()

**Comment by arcans** [comment]
I saw that icon but it is not enabled.
https://ibb.co/tXLGytD
https://ibb.co/Zgkh5Y1

**Comment by arcans** [comment]
[SOLVED]
Thanks for this thread.
https://linuxhint.com/pulse_audio_sounds_ubuntu/

I entered this command
>> sudo apt install pulseaudio

**Comment by tuanpham-dev** [comment]
Glad you fixed it
