### ISSUE TITLE
Firefox page crashed

### ISSUE THREAD

**Issue by arcans** [tuanpham-dev/termux-ubuntu#14]
I installed Firefox via this command
>> sudo apt install firefox

When opening any website (e.g "https://www.google.com"), the page tabs has crashed.

https://ibb.co/6Nn6CGd

Note: I already force stopped Termux/ killing vnc/ uninstalling firefox and relaunch, restore, close Firefox page tabs but the problem is still the same.

**Comment by arcans** [comment]
[SOLVED]
https://github.com/termux/proot/issues/139

**Comment by tuanpham-dev** [comment]
Glad you fixed it
