### ISSUE TITLE
AppImage (No such file or Directory)

### ISSUE THREAD

**Issue by arcans** [tuanpham-dev/termux-ubuntu#15]
I was trying to execute .AppImage files but it failed.
I tried this command under Downloads directory
>> chmod 777 UnityHub.AppImage

Result after executing "./UnityHub.AppImage" is:
>> No such file or directory

https://ibb.co/5GQ3v0S

**Comment by tuanpham-dev** [comment]
@arcans - Are you sure it includes version for ARM64?

**Comment by arcans** [comment]
> @arcans - Are you sure it includes version for ARM64?

Thanks, it doesn't support arm64
