### ISSUE TITLE
dbus socket is not found black screen during remote vnc

### ISSUE THREAD

**Issue by reidsneo** [tuanpham-dev/termux-ubuntu#2]
Android  10
Host: samsung SM-P615
Kernel: 4.14.113-19529942
Cpu: (8) @ 1.742GHz
Memory: 2274MiB / 3575MiB

dde package installed sucessfully by adding apt-add-repository manually

Log
You chose dynamic resolution

New 'remote-desktop' desktop at :1 on machine localhost

Starting applications specified in /home/reids/.vnc/xstartup
Log file is /home/reids/.vnc/localhost:1.log

Use xtigervncviewer -SecurityTypes VncAuth,TLSVnc -passwd /home/reids/.vnc/passwd localhost:1 to connect to the VNC server.

VNC server started. The default password is the account password for reids
reids@localhost:~$ startdde
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
failed to list backlight controller: open /sys/class/backlight: no such file or directory
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
backend_syslog.go:45: <info> syslog is not available: Unix syslog delivery error
<info> manager.go:630: [updateMonitors] add monitor: VNC-0 0 0 1900 1200
<error> xsettings.go:243: Start xsettings failed: dial unix /var/run/dbus/system_bus_socket: connect: connection refused
  ->  main.go:100
  ->  proc.go:203
  ->  asm_arm64.s:1128
<warning> main.go:103: dial unix /var/run/dbus/system_bus_socket: connect: connection refused
<warning> main.go:119: dial unix /var/run/dbus/system_bus_socket: connect: connection refused
reids@localhost:~$ ps
Error: /proc must be mounted
  To mount /proc at boot you need an /etc/fstab line like:
      proc   /proc   proc    defaults
  In the meantime, run "mount proc /proc -t proc"
reids@localhost:~$

**Comment by tuanpham-dev** [comment]
Hi, this was my experiment for testing if Deepin Desktop is installable. Now I reverted back to XFCE to avoid any confusion. I will update to Deepin Desktop later.
