### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by nnt12345** [tuanpham-dev/termux-ubuntu#27]
proot warning: can't chdir("/root/.") in the guest rootfs: No such file or directory
proot info: default working directory is now "/"
proot error: '/usr/bin/env' not found (root = /data/data/com.termux/files/home/jails/ubuntu/ubuntu-fs, cwd = /, $PATH=(null))
fatal error: see `proot --help`.

**Comment by tuanpham-dev** [comment]
@nnt12345 - It is still working for me, could you try it again. Please make sure you run `pkg update && pkg upgrade` before running installation command.

**Comment by SomeTroller77** [comment]
It's not working for me aswell after doing ```pkg update && pkg upgrade```
