### ISSUE TITLE
Lxde

### ISSUE THREAD

**Issue by Bobombn64** [tuanpham-dev/termux-ubuntu#28]
can you pls try make a script for the lxde DE?

**Comment by themoonmeetsthesun** [comment]
I think you can do it but then you need to edit the vnc startup script to get it running.

**Comment by tuanpham-dev** [comment]
@Bobombn64 - Could you try this command and let me know if it works for you?
```
pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/ubuntu.sh && chmod +x ubuntu.sh && bash ubuntu.sh lxde
```

**Comment by Bobombn64** [comment]
It seems to work fine, but it gave me this error. I saw it several times in the setup too
![Screenshot_2022-02-23-17-19-43-691_com iiordanov bVNC](https://user-images.githubusercontent.com/83509013/155361415-bb431519-47d3-4578-ac9a-3a0dc32c0143.jpg)

**Comment by Bobombn64** [comment]
> It seems to work fine, but it gave me this error. I saw it several times in the setup too ![Screenshot_2022-02-23-17-19-43-691_com iiordanov bVNC](https://user-images.githubusercontent.com/83509013/155361415-bb431519-47d3-4578-ac9a-3a0dc32c0143.jpg)

![Uploading Screenshot_2022-02-23-17-25-43-606_com.termux.jpg…]()

**Comment by tuanpham-dev** [comment]
@Bobombn64  - Please try again

**Comment by Bobombn64** [comment]
@tuanpham-dev thank you so much it's now working perfectly fine, and it runs better than xfce4, that's also why i wanted it.
Lxde is way better for people that don't have a powerful Device or just want to get the best performance and having a simple DE.

Everything i tried worked perfectly fine so far^^

**Comment by tuanpham-dev** [comment]
@Bobombn64 - Nice to hear it.
I am closing out this issue. Feel free to re-open it if there is any problem.
