### ISSUE TITLE
Audio Support

### ISSUE THREAD

**Issue by sepehrmoh81** [tuanpham-dev/termux-ubuntu#3]
I see that pulseaudio isn't installed, but there is pavucontrol which shows OpenSL ES Output. I'm trying to figure out how this works, and I assume this is a loopback monitor streamed over TCP. The problem is that I can't find the port set for streaming.
I'm trying to play audio using SImple Protocol Player and I already tried port 4712 and 8000 but no luck.

**Comment by tuanpham-dev** [comment]
Hi @sepehrmoh81 - Actually pulseaudio is installed. I used `setup-audio.sh` (which is encoded) to set up audio. For more information, check these:
- https://docs.andronix.app/hardware/sound
- https://android.stackexchange.com/questions/205576/how-to-play-sound-from-termux-when-using-linux
