### ISSUE TITLE
HELP!! cant connect to raw.github.......

### ISSUE THREAD

**Issue by Crossshield45** [tuanpham-dev/termux-ubuntu#34]
termux is not connecting to raw.github.......(it says connecting but does nothing ),does it take a long time to connect? i need help before this week ends

**Comment by Crossshield45** [comment]
> termux is not connecting to raw.github.......(it says connecting but does nothing ),does it take a long time to connect? i need help before this week ends

HELP NEEDED

**Comment by Mr-parfect** [comment]
raw.github.......this url I think ban in India or server problem use vpn to connect this

**Comment by Crossshield45** [comment]
Thanks for solution..
