### ISSUE TITLE
Using a different DE instead of xfce (for example gnome)

### ISSUE THREAD

**Issue by devlocalhost** [tuanpham-dev/termux-ubuntu#5]
I just installed this script on my phone, and using it on my laptop via vnc, but there's a problem. I tried to install gnome and then after logging out I got a black screen. Is it possible to install a different DE instead of xfce? If yes, how? Thanks

**Comment by tuanpham-dev** [comment]
@devlocalhost - I don't think gnome desktop is installable, I got errors on some packages. However if you can fix them, feel free to create a PR. FYI, you can install ubuntu without desktop environment to add another DE with this command:
```bash
pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/ubuntu.sh && chmod +x ubuntu.sh && bash ubuntu.sh nde
```

**Comment by devlocalhost** [comment]
> @devlocalhost - I don't think gnome desktop is installable, I got errors on some packages. However if you can fix them, feel free to create a PR. FYI, you can install ubuntu without desktop environment to add another DE with this command:
> 
> ```shell
> pkg update -y && pkg install wget curl proot tar -y && wget https://raw.githubusercontent.com/tuanpham-dev/termux-ubuntu/master/ubuntu.sh && chmod +x ubuntu.sh && bash ubuntu.sh nde
> ```

Alright, thanks. I'll see what I can do
